### ISSUE TITLE
Add NeutralinoJS

### ISSUE THREAD

**Issue by jetibest** [xpdanet/xpdanet.github.io#50]
[NeutralinoJS](https://neutralino.js.org/) is just a small client/webserver (~1MiB), to run a local website, including Javascript library for native OS implementation. Should work on Windows, Linux, and MacOS (it will use WebView from installed browser or web-library).

Main disadvantage compared to NW.js and Electron is a less consistent UI, but the consistency is similar to any hosted webapp.

**Comment by TheJaredWilcurt** [comment]
https://xpda.net/#NeutralinoJs
